### ISSUE TITLE
How to get drawing offsets and position for digital handwriting recognizer?

### ISSUE THREAD

**Issue by sujanbhattaraiofficial** [fyzo-dev/scribble#29]
Hello there,

I'm going to make an app that can recognize text from digital ink written in scribble but I'm unable to figure out the local positions and offsets.

**Comment by stevenhansel** [comment]
@sujanbhattaraiofficial I'm planning to use this library for a similar usecase, I'm able to get the sketch position by using `notifier.currentSketch`, you can also turn it into a json format, `notifier.currentSketch.toJson()`. I think you can benefit by trying to run the example provided in the repository itself, https://github.com/fyzo-dev/scribble/blob/develop/example/lib/main.dart
